package gui;

import javax.swing.*;
import java.awt.*;

public class GiudiciGui {
    private JPanel giudiciGui;
    private JButton button1;

    public GiudiciGui() {
        System.out.println("GiudiciGui");
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        giudiciGui = new JPanel();
        giudiciGui.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        button1 = new JButton();
        button1.setText("Button");
        giudiciGui.add(button1);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return giudiciGui;
    }

}
